apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: no-policy-violation
spec:
  kinds:
    - apiGroups: [""]
      kinds: ["ConfigMap"]
  parameters:
    labels:
      - team